#version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /data/dockerVolumes/maria/db:/var/lib/mysql
      - /data/dockerVolumes/maria/logs:/var/log/mysql
      - /data/dockerVolumes/maria/my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"