# 数据库配置
PORTAL = "mariadb+asyncmy"
USERNAME = "blog_dba"
PASSWORD = "blog_dba"
HOST = "192.168.17.129"
PORT = "3306"
DATABASE = "blog_site"
DB_URI = f"{PORTAL}://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
# 密钥配置
JWT_KEY = r'O_Q58<z5n,\{m<DSyFv$WycR2x{TRn0j66/63bA?1w0joq_&=FO1Xc5X[E7T0-#2'
SESSION_KEY = r'Zo5O~Ov?d9q#^AsU6j(A1G-z$1d-L833'
# 日志配置
ENABLE_ACCESS_LOG = True
ENABLE_ACCESS_LOG_FILE = True
ENABLE_ACCESS_LOG_CONSOLE = True
ENABLE_AUDIT_LOG = True
ENABLE_AUDIT_LOG_FILE = True
ENABLE_AUDIT_LOG_CONSOLE = True
ENABLE_ERROR_LOG = True
ENABLE_ERROR_LOG_FILE = True
ENABLE_ERROR_LOG_CONSOLE = False
# 其它配置
NICKNAME_ENCODING = 'gbk'
